define([
    'services/ui/navigation-service',
    'services/ui/loading-service',
    'services/config-service',
    'services/data/resource-service',
    'services/data/autocomplete-service',
    'services/data/summary-service',
    'services/auth/auth-service',
    'services/data/reports-service'
],function(){
    return angular.module('app.services',[
        'app.services.ui.navigation',
        'app.services.ui.loading',
        'app.services.config',
        'app.services.data.resources',
        'app.services.autocomplete',
        'app.services.summary',
        'app.services.auth',
        'app.services.reports'
    ]);
});
